/*
  mitsubishi2mqtt - Mitsubishi Heat Pump to MQTT control for Home Assistant.
  Copyright (c) 2019 gysmo38, dzungpv, shampeon, endeavour, jascdk, chrdavis, alekslyse.  All right reserved.
  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.
  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
 
const char html_common_header[] PROGMEM = 
"<!DOCTYPE html>"
"<html lang='en' class=''>"
"<head>"
    "<meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no' />"
    "<title>_APP_NAME_ - _UNIT_NAME_</title>"
    "<style>"
        ":root {"
            "/* Light mode variables */"
            "--bg-color: #ffffff;"
            "--text-color: #000000;"
            "--fieldset-bg: #f2f2f2;"
            "--select-bg: #dddddd;"
            "--select-color: #000000;"
            "--textarea-bg: #f8f8f8;"
            "--textarea-border: #ccc;"
            "--button-bg: #1fa3ec;"
            "--button-hover: #0e70a4;"
            "--button-red-bg: #d43535;"
            "--button-red-hover: #931f1f;"
            "--button-green-bg: #47c266;"
            "--button-green-hover: #5aaf6f;"
            "--switch-bg: #ccc;"
            "--switch-active: #0c0;"
            "--switch-focus: #2196f3;"
        "}"
        "@media (prefers-color-scheme: dark) {"
            ":root {"
                "/* Dark mode variables */"
                "--bg-color: #1a1a1a;"
                "--text-color: #ffffff;"
                "--fieldset-bg: #2d2d2d;"
                "--select-bg: #404040;"
                "--select-color: #ffffff;"
                "--textarea-bg: #2d2d2d;"
                "--textarea-border: #555555;"
                "--button-bg: #2563eb;"
                "--button-hover: #1d4ed8;"
                "--button-red-bg: #dc2626;"
                "--button-red-hover: #b91c1c;"
                "--button-green-bg: #16a34a;"
                "--button-green-hover: #15803d;"
                "--switch-bg: #555555;"
                "--switch-active: #22c55e;"
                "--switch-focus: #3b82f6;"
            "}"
        "}"
        "* {"
            "font-family: verdana, sans-serif;"
        "}"
        "body {"
            "text-align: center;"
            "background-color: var(--bg-color);"
            "color: var(--text-color);"
            "transition: background-color 0.3s ease, color 0.3s ease;"
        "}"
        "div,"
        "fieldset,"
        "input,"
        "select {"
            "padding: 5px;"
            "font-size: 1em;"
        "}"
        ".main {"
            "text-align: left;"
            "display: inline-block;"
            "min-width: 340px;"
        "}"
        "fieldset {"
            "background-color: var(--fieldset-bg);"
            "border-color: var(--textarea-border);"
            "transition: background-color 0.3s ease;"
        "}"
        "p {"
            "margin: 0.5em 0;"
        "}"
        ".ctrlrow {"
            "padding: 0px !important;"
            "margin: 0.5em 0 !important;"
        "}"
        "input {"
            "width: 100%;"
            "box-sizing: border-box;"
            "-webkit-box-sizing: border-box;"
            "-moz-box-sizing: border-box;"
            "background-color: var(--bg-color);"
            "color: var(--text-color);"
            "border: 1px solid var(--textarea-border);"
            "transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;"
        "}"
        "input[type=checkbox],"
        "input[type=radio] {"
            "width: 1em;"
            "margin-right: 6px;"
            "vertical-align: -1px;"
        "}"
        "select {"
            "width: 100%;"
            "background: var(--select-bg);"
            "color: var(--select-color);"
            "block-size: 40px;"
            "border: 1px solid var(--textarea-border);"
            "transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;"
        "}"
        "textarea {"
            "resize: true;"
            "width: 100%;"
            "height: 50px;"
            "padding: 5px;"
            "box-sizing: border-box;"
            "border: 2px solid var(--textarea-border);"
            "border-radius: 4px;"
            "background-color: var(--textarea-bg);"
            "color: var(--text-color);"
            "overflow: auto;"
            "transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;"
        "}"
        "td {"
            "padding: 0px;"
        "}"
        "button {"
            "border: 0;"
            "border-radius: 0.3rem;"
            "background-color: var(--button-bg);"
            "color: #fff;"
            "line-height: 2.4rem;"
            "font-size: 1.2rem;"
            "width: 100%;"
            "-webkit-transition-duration: 0.4s;"
            "transition-duration: 0.4s;"
            "cursor: pointer;"
        "}"
        "button:hover {"
            "background-color: var(--button-hover);"
        "}"
        ".bred {"
            "background-color: var(--button-red-bg);"
        "}"
        ".bred:hover {"
            "background-color: var(--button-red-hover);"
        "}"
        ".bgrn {"
            "background-color: var(--button-green-bg);"
        "}"
        ".bgrn:hover {"
            "background-color: var(--button-green-hover);"
        "}"
        "a {"
            "text-decoration: none;"
            "color: var(--text-color);"
        "}"
        ".p {"
            "float: left;"
            "text-align: left;"
        "}"
        ".q {"
            "float: right;"
            "text-align: right;"
        "}"
        "pan {"
            "display: inline-block;"
        "}"
        "/* ON/OFF switch */"
        "/* The switch - the box around the slider */"
        ".switch {"
            "position: relative;"
            "display: inline-block;"
            "width: 60px;"
            "height: 34px;"
        "}"
        "/* Hide default HTML checkbox */"
        ".switch input {"
            "opacity: 0;"
            "width: 0;"
            "height: 0;"
        "}"
        "/* The slider */"
        ".slider {"
            "position: absolute;"
            "cursor: pointer;"
            "top: 0;"
            "left: 0;"
            "right: 0;"
            "bottom: 0;"
            "background-color: var(--switch-bg);"
            "-webkit-transition: 0.4s;"
            "transition: 0.4s;"
        "}"
        ".slider:before {"
            "position: absolute;"
            "content: '';"
            "height: 26px;"
            "width: 26px;"
            "left: 4px;"
            "bottom: 4px;"
            "background-color: white;"
            "-webkit-transition: 0.4s;"
            "transition: 0.4s;"
        "}"
        "input:checked + .slider {"
            "background-color: var(--switch-active);"
        "}"
        "input:focus + .slider {"
            "box-shadow: 0 0 1px var(--switch-focus);"
        "}"
        "input:checked + .slider:before {"
            "-webkit-transform: translateX(26px);"
            "-ms-transform: translateX(26px);"
            "transform: translateX(26px);"
        "}"
        "/* Rounded sliders */"
        ".slider.round {"
            "border-radius: 34px;"
        "}"
        ".slider.round:before {"
            "border-radius: 50%;"
        "}"
    "</style>"
"</head>"
"<body>"
  "<div class='main'>"
    "<div style='text-align:center;'>"
        "<noscript>To user _APP_NAME_, you need to activate Javascript"
                "<br/>"
        "</noscript>"
        "<h3>_UNIT_NAME_</h3>"
     "</div>";

const char html_common_footer[] PROGMEM = 
    "<br/>"
    "<div style='text-align:right;font-size:10px;color: grey;'>"
       "<hr/>_APP_NAME_ _VERSION_</div>"
    "</div>"
  "</div>"
"</body>"
"</html>";