on:
  push:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ github.workspace }}/app

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Generic8266(ESP-01)
        run: |
          cd ${{ github.workspace }}/app
          pio run -e ESP8266-ESP01
          mv .pio/build/ESP8266-ESP01/firmware.bin mitsubishi2MQTT_ESP8266-ESP01.bin

      - name: Build WEMOS_D1_Mini
        run: |
          cd ${{ github.workspace }}/app
          pio run -e WEMOS_D1_Mini
          mv .pio/build/WEMOS_D1_Mini/firmware.bin mitsubishi2MQTT_WEMOS_D1_Mini.bin

      - name: Build PIO ESP32DEV
        run: |
          cd ${{ github.workspace }}/app
          pio run -e ESP32DEV
          mv .pio/build/ESP32DEV/firmware.bin mitsubishi2MQTT_ESP32DEV_PIO.bin

      - name: Upload esp8266 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mitsubishi2MQTT_ESP8266-ESP01.bin
          path: ${{ github.workspace }}/app/mitsubishi2MQTT_ESP8266-ESP01.bin

      - name: Upload WEMOS_D1_Mini artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mitsubishi2MQTT_WEMOS_D1_Mini.bin
          path: ${{ github.workspace }}/app/mitsubishi2MQTT_WEMOS_D1_Mini.bin

      - name: Upload PIO esp32dev artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mitsubishi2MQTT_ESP32DEV_PIO.bin
          path: ${{ github.workspace }}/app/mitsubishi2MQTT_ESP32DEV_PIO.bin

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.6
          target: esp32
          path: app
          command: apt-get update && apt-get install -y python3-venv && idf.py build
          
      - name: Merge all bin file to one 
        run: |
           cd ${{ github.workspace }}/app/build && esptool.py --chip esp32 merge_bin -o mitsubishi2MQTT_ESP32DEV_IDF.bin --flash_mode dio --flash_freq 40m --flash_size 4MB 0x1000 bootloader/bootloader.bin 0x20000 mitsubishi2MQTT.bin 0xe000 partition_table/partition-table.bin 0x1d000 ota_data_initial.bin
      # - name: Rename IDF bin file
      #   run: |
      #     sudo mv ${{ github.workspace }}/app/build/mitsubishi2MQTT.bin ${{ github.workspace }}/app/build/mitsubishi2MQTT_ESP32DEV_IDF.bin
      - name: Upload ESP32DEV_IDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mitsubishi2MQTT_ESP32DEV_IDF.bin
          path: |
            ${{ github.workspace }}/app/build/mitsubishi2MQTT_ESP32DEV_IDF.bin 
